/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/ban-ts-comment, @typescript-eslint/no-unused-vars */
import { deployContract } from '@midnight-ntwrk/midnight-js-contracts';
import { CompiledContract } from '@midnight-ntwrk/compact-js';
// @ts-expect-error Upstream package issues
import { NodeZkConfigProvider } from '@midnight-ntwrk/midnight-js-node-zk-config-provider';
// @ts-expect-error Upstream package issues
import { indexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
// @ts-expect-error Upstream package issues
import { httpClientProofProvider } from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
// @ts-expect-error Upstream package issues
import { levelPrivateStateProvider } from '@midnight-ntwrk/midnight-js-level-private-state-provider';
import { setNetworkId } from '@midnight-ntwrk/midnight-js-network-id';
import * as path from 'path';
import * as dotenv from 'dotenv';
import pino from 'pino';

// Load environment variables
dotenv.config({ path: '.env.local' });

// Workaround for Node.js WebSocket requirement in Midnight SDK
import { WebSocket } from 'ws';
globalThis.WebSocket = WebSocket as unknown as typeof globalThis.WebSocket;

// The bindings will be generated by the `compact` compiler
// @ts-ignore
import { Contract, PrivateInferPrivateStateId, PrivateInferPrivateState } from '../contracts/managed/privateinfer/index.js';

async function main() {
  const logger = pino({ level: 'info' });
  logger.info("Initializing Midnight deployment...");

  // 1. Configure network
  setNetworkId('undeployed'); // Change to 'preview' for testnet
  
  // Note: For a real deployment on Preview, you would initialize 
  // HDWallet, ShieldedWallet, and UnshieldedWallet here using your seed.
  // We use the testkit or mock providers for local development.

  // 2. Load compiled ZK assets
  const zkConfigPath = path.resolve('contracts/managed/privateinfer');
  const compiledContract = CompiledContract.make('privateinfer', Contract).pipe(
    CompiledContract.withVacantWitnesses,
    CompiledContract.withCompiledFileAssets(zkConfigPath),
  );

  console.log("Ready to deploy. Please connect a valid WalletProvider to deploy.");
  console.log("Run `compact compile contracts/privateinfer.compact contracts/managed/privateinfer` first!");
  
  // Deployment logic goes here using `deployContract(providers, { ... })`
}

main().catch(console.error);
