/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/ban-ts-comment */
import { Redis } from '@upstash/redis';
import { PrismaClient } from '@prisma/client';
import { Pool } from '@neondatabase/serverless';
import { PrismaNeon } from '@prisma/adapter-neon';
import * as dotenv from 'dotenv';
import * as crypto from 'crypto';

dotenv.config({ path: '.env' });

const neon = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaNeon(neon as any);
const prisma = new PrismaClient({ adapter: adapter as any });

const redis = new Redis({
  url: process.env.UPSTASH_REDIS_REST_URL!,
  token: process.env.UPSTASH_REDIS_REST_TOKEN!,
});

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

/**
 * PrivateInfer Simulated Inference Engine
 *
 * This is a deterministic, hash-driven inference simulation. In a production
 * deployment, this function would call a private LLM endpoint (e.g. an
 * air-gapped ONNX runtime, or a TEE-hosted LLaMA instance).
 *
 * The critical property here is that the proofHash is deterministically derived
 * from the query input hash — so the same query always produces the same proof,
 * and different queries produce different proofs. This is the foundation of
 * the verifiability guarantee that the Compact on-chain circuit enforces.
 */
function runMedicalInference(queryInputHash: string) {
  // Derive a query-specific seed from the input hash
  const seed = parseInt(queryInputHash.slice(0, 8), 16);

  // Generate a per-query confidence score (deterministic from input)
  const confidence = (85 + (seed % 15)).toFixed(1);

  // Select a diagnosis category deterministically from the input hash
  const categories = [
    "Upper respiratory tract infection (URI)",
    "Seasonal allergic rhinitis",
    "Viral pharyngitis",
    "Tension-type headache",
    "Acute sinusitis",
    "Musculoskeletal strain",
    "Gastroesophageal reflux (GERD)",
    "Benign positional vertigo",
  ];
  const categoryIndex = seed % categories.length;
  const primaryDiagnosis = categories[categoryIndex];

  const inference = [
    `Primary assessment: ${primaryDiagnosis}.`,
    `Confidence: ${confidence}%.`,
    `Based on the encrypted symptom parameters, the PrivateInfer model identified ${primaryDiagnosis} as the most probable diagnosis.`,
    `Recommendation: Consult a licensed physician for confirmation. This output is a privacy-preserving inference result generated by the PrivateInfer system and does not constitute medical advice.`,
    `Query hash: ${queryInputHash.slice(0, 16)}...`,
  ].join(' ');

  // Build a deterministic, verifiable proof hash:
  // proofHash = SHA-256(queryInputHash + inference_output)
  // This links the specific input to the specific output — tamper-evident and reproducible.
  const proofPayload = queryInputHash + inference;
  const proofHash = crypto.createHash('sha256').update(proofPayload).digest('hex');

  // Result hash = SHA-256(inference_output) — used as the on-chain resultHash in the Compact contract
  const resultHash = crypto.createHash('sha256').update(inference).digest('hex');

  return { inference, proofHash, resultHash };
}

async function main() {
  console.log("PrivateInfer Worker started. Listening to 'inference_queue'...");

  while (true) {
    try {
      const job = await redis.rpop("inference_queue");

      if (!job) {
        await sleep(2000);
        continue;
      }

      const { queryId, encryptedBlob } = typeof job === 'string' ? JSON.parse(job) : job;
      console.log(`[Worker] Processing query ${queryId}...`);

      await prisma.query.update({
        where: { id: queryId },
        data: { status: "PROCESSING" }
      });

      // Simulate inference latency (GPU processing time)
      await sleep(3500);

      // Use the encrypted blob (which is the SHA-256 commitment of the user's query)
      // as the input to make the result deterministically bound to the query content.
      const inputHash = encryptedBlob || crypto.createHash('sha256').update(queryId).digest('hex');
      const { inference, proofHash, resultHash } = runMedicalInference(inputHash);

      // Check if a result record already exists (avoid duplicate insert)
      const existing = await prisma.result.findUnique({ where: { queryId } });

      await prisma.query.update({
        where: { id: queryId },
        data: {
          status: "RESULT_READY",
          commitmentHash: resultHash,
          ...(!existing && {
            result: {
              create: {
                decryptedData: inference,
                proofHash: proofHash,
              }
            }
          }),
        }
      });

      console.log(`[Worker] Inference complete for ${queryId}. proofHash=${proofHash.slice(0, 16)}... Status set to RESULT_READY. Awaiting provider on-chain submission.`);

    } catch (e) {
      console.error("[Worker] Error:", e);
      await sleep(5000);
    }
  }
}

main();
